// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXAdIbJ2wFbitaJXF4ZudTxHLD0wltVvc',
    appId: '1:432155177903:web:93c9f9c30656da070d755a',
    messagingSenderId: '432155177903',
    projectId: 'daily-log-59cfa',
    authDomain: 'daily-log-59cfa.firebaseapp.com',
    storageBucket: 'daily-log-59cfa.appspot.com',
    measurementId: 'G-W29MVHQZXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgipxcP2e8ip11tf55hiMpykT6us5ERVs',
    appId: '1:432155177903:android:eb35c565433266380d755a',
    messagingSenderId: '432155177903',
    projectId: 'daily-log-59cfa',
    storageBucket: 'daily-log-59cfa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5wrU9R_2g9n9cLdU30qPrBDHtXXKtHtM',
    appId: '1:432155177903:ios:b611cc8be82dd0570d755a',
    messagingSenderId: '432155177903',
    projectId: 'daily-log-59cfa',
    storageBucket: 'daily-log-59cfa.appspot.com',
    iosBundleId: 'com.example.try2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5wrU9R_2g9n9cLdU30qPrBDHtXXKtHtM',
    appId: '1:432155177903:ios:5e4f6a8a859768bb0d755a',
    messagingSenderId: '432155177903',
    projectId: 'daily-log-59cfa',
    storageBucket: 'daily-log-59cfa.appspot.com',
    iosBundleId: 'com.example.try2.RunnerTests',
  );
}
